version: "3.8"

services:

  database:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=assessment
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'

volumes:
  database:
